org: betalogika
app: halokak-be-node
service: halokak-be-node

frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 3008
  timeout: 30
  environment:
    NODE_ENV: ${opt:stage, 'dev'}

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-offline-scheduler

functions:
  - ${file(app/example/example.serverless.yml)}
  - ${file(app/authentication/authentication.serverless.yml)}
  - ${file(app/Mentor/Mentor.serverless.yml)}